<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Attendance Summary</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            color: #6b7280;
            margin: 5px 0 0 0;
        }
        .summary-stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
        }
        .stat-item {
            text-align: center;
        }
        .stat-number {
            font-size: 24px;
            font-weight: bold;
            color: #1e40af;
        }
        .stat-label {
            color: #6b7280;
            font-size: 14px;
        }
        .department-stats {
            margin-bottom: 30px;
        }
        .department-stats h2 {
            color: #1e40af;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 10px;
        }
        .dept-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .dept-table th,
        .dept-table td {
            border: 1px solid #d1d5db;
            padding: 12px;
            text-align: left;
        }
        .dept-table th {
            background-color: #f3f4f6;
            font-weight: bold;
            color: #374151;
        }
        .dept-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .attendance-rate {
            font-weight: bold;
        }
        .rate-high { color: #059669; }
        .rate-medium { color: #d97706; }
        .rate-low { color: #dc2626; }
        .footer {
            margin-top: 40px;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Weekly Attendance Summary</h1>
        <p>Report Period: {{ $weekStart }} - {{ $weekEnd }}</p>
        <p>Generated on: {{ now()->format('M d, Y \a\t H:i') }}</p>
    </div>

    <div class="summary-stats">
        <div class="stat-item">
            <div class="stat-number">{{ $totalRecords }}</div>
            <div class="stat-label">Total Records</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $presentCount }}</div>
            <div class="stat-label">Present</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $absentCount }}</div>
            <div class="stat-label">Absent</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $lateCount }}</div>
            <div class="stat-label">Late</div>
        </div>
    </div>

    <div class="department-stats">
        <h2>Department Breakdown</h2>
        <table class="dept-table">
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Total Records</th>
                    <th>Present</th>
                    <th>Attendance Rate</th>
                </tr>
            </thead>
            <tbody>
                @forelse($departmentStats as $dept)
                <tr>
                    <td>{{ $dept['department'] }}</td>
                    <td>{{ $dept['total_records'] }}</td>
                    <td>{{ $dept['present_count'] }}</td>
                    <td class="attendance-rate 
                        @if($dept['attendance_rate'] >= 80) rate-high
                        @elseif($dept['attendance_rate'] >= 60) rate-medium
                        @else rate-low
                        @endif">
                        {{ $dept['attendance_rate'] }}%
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" style="text-align: center; color: #6b7280;">No attendance data available for this week</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This report was automatically generated by SmartAttend System</p>
        <p>For questions or support, please contact the system administrator</p>
    </div>
</body>
</html>
